x-common-certificate: &common-certificate
  ${SERVER_SSL_CERTIFICATE}:${SERVER_SSL_CERTIFICATE}
x-common-certificate-private-key: &common-certificate-private-key
  ${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}:${SERVER_SSL_CERTIFICATE_PRIVATE_KEY}
services:
  grafana:
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
      GF_SERVER_PROTOCOL: https
      GF_SERVER_CERT_FILE: $SERVER_SSL_CERTIFICATE
      GF_SERVER_CERT_KEY: $SERVER_SSL_CERTIFICATE_PRIVATE_KEY
    image: grafana/grafana:12.2.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    user: root
    volumes:
      - /home/outsideworx/grafana:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - *common-certificate
      - *common-certificate-private-key
  loki:
    container_name: loki
    image: grafana/loki:3.5.5
    restart: unless-stopped
    user: root
    volumes:
      - /home/outsideworx/loki:/loki
      - ./loki.yaml:/etc/loki/config.yml
  ntfy:
    command: serve
    container_name: ntfy
    environment:
      NTFY_CERT_FILE: $SERVER_SSL_CERTIFICATE
      NTFY_KEY_FILE: $SERVER_SSL_CERTIFICATE_PRIVATE_KEY
      NTFY_WEB_PUSH_PUBLIC_KEY: $NTFY_WEB_PUSH_PUBLIC_KEY
      NTFY_WEB_PUSH_PRIVATE_KEY: $NTFY_WEB_PUSH_PRIVATE_KEY
    image: binwiederhier/ntfy:v2.15.0
    ports:
      - "3001:3001"
    volumes:
      - /home/outsideworx/ntfy:/etc/ntfy/data
      - ./ntfy.yaml:/etc/ntfy/server.yml
      - *common-certificate
      - *common-certificate-private-key
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: $SPRING_DATASOURCE_USERNAME
      POSTGRES_PASSWORD: $SPRING_DATASOURCE_PASSWORD
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - /home/outsideworx/data:/var/lib/postgresql/data
  postgres-exporter:
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: postgres:5432/?sslmode=disable
      DATA_SOURCE_USER: $SPRING_DATASOURCE_USERNAME
      DATA_SOURCE_PASS: $SPRING_DATASOURCE_PASSWORD
    image: prometheuscommunity/postgres-exporter:v0.18.1
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.6.0
    restart: unless-stopped
    user: root
    volumes:
      - /home/outsideworx/prometheus:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  vault:
    build: .
    container_name: vault
    depends_on:
      - loki
      - postgres
    env_file:
      - .env
    ports:
      - "443:443"
    restart: on-failure:4
    volumes:
      - *common-certificate
      - *common-certificate-private-key