global:
  scrape_interval: 1m
scrape_configs:
  - job_name: loki
    static_configs:
      - targets: [ "loki:3100" ]
  - job_name: ntfy
    static_configs:
      - targets: [ "ntfy" ]
  - job_name: node-exporter
    static_configs:
      - targets: [ "node-exporter:9100" ]
  - job_name: postgres-exporter
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
  - job_name: sites
    static_configs:
      - targets: [
        "come-in-and-find-out",
        "duckumbrella",
        "gaiapeeps",
        "igli",
        "outsideworx",
        "soupart",
        "soupkitchen"
      ]
  - job_name: vault
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ "vault" ]