app:
  clients:
    ciafo:
      caller: "come-in-and-find-out"
      origin: "https://sites.outsideworx.net:9001"
    peeps:
      caller: "gaiapeeps"
      origin: "https://sites.outsideworx.net:9003"
    soup:
      caller: "soupart"
      origin: "https://sites.outsideworx.net:9005"
  services:
    grafana:
      url: "https://services.outsideworx.net:3000"
    loki:
      url: "http://loki:3100"
    ntfy:
      url: "https://services.outsideworx.net:3001"
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  server:
    port: 80
    ssl:
      enabled: false
server:
  port: 443
  tomcat:
    max-part-count: 50
spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumWeight=201326592
  datasource:
    url: jdbc:postgresql://postgres:5432/
  jackson:
    default-property-inclusion: NON_EMPTY
  jpa:
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 64MB